apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations:
    deploy.cloud.google.com/labels:
      environment: dev
  labels:
    environment: dev
description: dev
gke:
  cluster: projects/<second-project-424720/locations/us-central1-c/clusters/dev-cluster
